name = "container-shapes"
version = "0.1.0"
defaultTargets = ["ContainerShapes"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.13.0"

[[lean_lib]]
name = "ContainerShapes"
globs = [
  "Container.*",
]
